BUNDLE_NAME = GommirativPreferences
GommirativPreferences_FILES = GommirativRootListController.m
GommirativPreferences_FRAMEWORKS = UIKit Foundation
GommirativPreferences_PRIVATE_FRAMEWORKS = Preferences
GommirativPreferences_INSTALL_PATH = /Library/PreferenceBundles
GommirativPreferences_CFLAGS = -fobjc-arc

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/bundle.mk
